version: "1.0"

services:
  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/bitnami/redis/data

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: 'sssg'
      MYSQL_USER: 'sumo'
      MYSQL_PASSWORD: 'jumbo'
      MYSQL_ROOT_PASSWORD: 'jumbo'
      TZ: 'Asia/Kolkata'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
